# Generated by Django 5.0.1 on 2025-11-26 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAnalysis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('columns', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'temp_analysis',
            },
        ),
        migrations.CreateModel(
            name='PDFOperation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation_type', models.CharField(choices=[('merge', 'Merge PDF'), ('split', 'Split PDF'), ('compress', 'Compress PDF'), ('protect', 'Protect PDF'), ('unlock', 'Unlock PDF'), ('rotate', 'Rotate PDF'), ('watermark', 'Watermark PDF'), ('organize', 'Organize PDF'), ('pdf_to_word', 'PDF to Word'), ('pdf_to_excel', 'PDF to Excel'), ('pdf_to_ppt', 'PDF to PowerPoint'), ('pdf_to_jpg', 'PDF to JPG'), ('jpg_to_pdf', 'JPG to PDF'), ('word_to_pdf', 'Word to PDF'), ('excel_to_pdf', 'Excel to PDF'), ('ppt_to_pdf', 'PowerPoint to PDF'), ('sign', 'Sign PDF'), ('edit', 'Edit PDF'), ('ocr', 'OCR PDF'), ('repair', 'Repair PDF'), ('page_numbers', 'Add Page Numbers'), ('compare', 'Compare PDF'), ('pdf_a', 'Convert to PDF/A')], max_length=50)),
                ('input_file_count', models.IntegerField(default=1)),
                ('input_file_size', models.BigIntegerField(default=0)),
                ('output_file_size', models.BigIntegerField(default=0)),
                ('processing_time', models.FloatField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
